all :
	g++ cpuVSgpu.cpp -o cpuVSgpu.out `pkg-config --libs opencv` `pkg-config --cflags opencv`
cpu :
	g++ cpu.cpp -o cpu.out `pkg-config --libs opencv` `pkg-config --cflags opencv`
gpu :
	g++ gpu.cpp -o gpu.out `pkg-config --libs opencv` `pkg-config --cflags opencv`
